package com.eframework.model.base;

import com.eframework.core.model.EModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBussWxEventMsg<M extends BaseBussWxEventMsg<M>> extends EModel<M> {

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setEventNo(java.lang.String eventNo) {
		set("event_no", eventNo);
	}

	public java.lang.String getEventNo() {
		return get("event_no");
	}

	public void setReplyMsg(java.lang.String replyMsg) {
		set("reply_msg", replyMsg);
	}

	public java.lang.String getReplyMsg() {
		return get("reply_msg");
	}

}
