package com.eframework.model.base;

import com.eframework.core.model.EModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBussAccountThirdparty<M extends BaseBussAccountThirdparty<M>> extends EModel<M> {

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public void setThirdpartyId(java.lang.Integer thirdpartyId) {
		set("thirdparty_id", thirdpartyId);
	}

	public java.lang.Integer getThirdpartyId() {
		return get("thirdparty_id");
	}

	public void setThirdpartyNo(java.lang.String thirdpartyNo) {
		set("thirdparty_no", thirdpartyNo);
	}

	public java.lang.String getThirdpartyNo() {
		return get("thirdparty_no");
	}

	public void setUnionNo(java.lang.String unionNo) {
		set("union_no", unionNo);
	}

	public java.lang.String getUnionNo() {
		return get("union_no");
	}

}
