package com.eframework.model.base;

import com.eframework.core.model.EModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBussAccountInfo<M extends BaseBussAccountInfo<M>> extends EModel<M> {

	public void setVersion(java.lang.Integer version) {
		set("version", version);
	}

	public java.lang.Integer getVersion() {
		return get("version");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public void setRoleId(java.lang.Integer roleId) {
		set("role_id", roleId);
	}

	public java.lang.Integer getRoleId() {
		return get("role_id");
	}

	public void setJob(java.lang.String job) {
		set("job", job);
	}

	public java.lang.String getJob() {
		return get("job");
	}

	public void setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
	}

	public java.lang.String getNickName() {
		return get("nick_name");
	}

	public void setPhoto(java.lang.String photo) {
		set("photo", photo);
	}

	public java.lang.String getPhoto() {
		return get("photo");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setAccountThirdpartyId(java.lang.Integer accountThirdpartyId) {
		set("account_thirdparty_id", accountThirdpartyId);
	}

	public java.lang.Integer getAccountThirdpartyId() {
		return get("account_thirdparty_id");
	}
	
	public void setMaterialFacId(java.lang.Integer material_fac_id) {
		set("material_fac_id", material_fac_id);
	}

	public java.lang.Integer getMaterialFacId() {
		return get("material_fac_id");
	}
	
	public void setInspectionUnitId(java.lang.Integer inspection_unit_id) {
		set("inspection_unit_id", inspection_unit_id);
	}

	public java.lang.Integer getInspectionUnitId() {
		return get("inspection_unit_id");
	}
	
	public void setRequestTime(java.util.Date requestTime) {
		set("request_time", requestTime);
	}

	public java.util.Date getRequestTime() {
		return get("request_time");
	}

}
